[package]
name = "DxeCoreDebugAgentLib"
version = "0.1.0"
edition = "2021"
authors = ["Microsoft"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_gdb_stub"
path = "gdb/lib.rs"
crate-type = ["staticlib"]

[dependencies]
r-efi = { workspace = true }
lazy_static = {version = "1.0.0", features = ["spin_no_std"]}
gdbstub = { version = "0.7.1", default-features = false }
gdbstub_arch  = { version = "0.3.0", default-features = false }
